package de.mpa.graphdb.edges;

public enum RelationType {
	HAS_PEPTIDE,
	IS_MATCH_IN,
	BELONGS_TO_TAXONOMY,
	BELONGS_TO_ENZYME,
	BELONGS_TO_PATHWAY,
	BELONGS_TO_EXPERIMENT,
	INVOLVED_IN_BIOPROCESS,
	BELONGS_TO_CELL_COMP,
	HAS_MOLECULAR_FUNCTION,
	BELONGS_TO,
	IS_SUPERGROUP_OF,
	IS_ANCESTOR_OF, 
	IS_METAPROTEIN_OF
}
