package de.mpa.io;

import java.util.TreeMap;

import junit.framework.TestCase;

import org.junit.Before;
import org.junit.Test;

public class SixtyFourBitStringDecoderTest extends TestCase {

	private String mzString, inString, chString;

	@Before
	public void setUp() {
		// BSA ESI Trap/BSA1.mgf - TITLE= Cmpd 10, +MSn(409.6854), 11.9 min
		mzString = "QFk6aIeo1k1AW4EbxVhkRUBftJN0vGp/QGAss9B8hLZAYh7P6be/H0BiSOSjgydnQGJe7dBSk0tAY12F23azvEBlhBQm/nGLQGWc64UeuFJAaKGuvECNj0BsHaODJ2dNQHBAPtUn5SFAcb6vrWy1NUBx1qcTakAQQHLf2Ur08NhAcxbUAksz20BzqSJdjXnRQHQ7Vv/BFd9AdM7lYEGJN0B2CNb1RLsbQHZQ2Lgn+hpAdqTV7x/d7EB201ar3j+8QHcQ4CIUJv5AdyFNvfj0c0B3YYmqo60ZQHepvGACnxdAeDrdgv114kB4Qp7NSqEOQHhs1VHWjGlAeHjWI42jwkB4ntitq59WQHk2zviLl3hAehzXSSeRP0B68bwWnCO4QHwq1e8f3exAfF6e18b70kB+ITWy1NQCQH522hysCDFAgClrDIikf0CAV30NBnjAQIDoZs9B8hNAgXntCRfWtkCBh2vjfek6QII6cBEKE39Agohs5GSZB0CDHGlzltCRQIOhE3S8an9AhDJHhCMP0ECEckpSaVlgQIUB1c+qzZ9AhsqXcxj8UECHWjFLnLaFQIeptE5QxetAh7lqdH2AXg==";
		inString = "QIRwAAAAAABArKQAAAAAAECLYAAAAAAAQJtQAAAAAABAuYsAAAAAAECAcAAAAAAAQLIBAAAAAABAoxgAAAAAAEB54AAAAAAAQNGowAAAAABAf5AAAAAAAEByYAAAAAAAQLAGAAAAAABAs7YAAAAAAEB9IAAAAAAAQJI8AAAAAABAf+AAAAAAAECypAAAAAAAQJ6EAAAAAABAdDAAAAAAAECEOAAAAAAAQHXAAAAAAABAmRAAAAAAAECWEAAAAAAAQJ4gAAAAAABAtn8AAAAAAEC7DwAAAAAAQK08AAAAAABAdvAAAAAAAECgpAAAAAAAQH4AAAAAAABAtxcAAAAAAEByYAAAAAAAQHKwAAAAAABAj5AAAAAAAECNcAAAAAAAQHiAAAAAAABAdOAAAAAAAECIoAAAAAAAQICwAAAAAABAyuQAAAAAAECJKAAAAAAAQHJgAAAAAABAj4AAAAAAAEB1cAAAAAAAQIOgAAAAAABAfNAAAAAAAEB2oAAAAAAAQJiAAAAAAABA6YXgAAAAAEClnAAAAAAAQLNDAAAAAABAikgAAAAAAECchAAAAAAAQKLMAAAAAABAgcAAAAAAAA==";
		chString = "AAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAQAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAABAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAA=";
	}

	@Test
	public void test64bitDecoding() {		
		double[] mzArray = SixtyFourBitStringSupport.decodeBase64StringToDoubles(mzString);
		double[] inArray = SixtyFourBitStringSupport.decodeBase64StringToDoubles(inString);
		int[] chArray = SixtyFourBitStringSupport.decodeBase64StringToInts(chString);
		
		TreeMap<Double, Double> peaks = new TreeMap<Double, Double>(SixtyFourBitStringSupport.buildPeakMap(mzArray, inArray));
		TreeMap<Double, Integer> charges = new TreeMap<Double, Integer>(SixtyFourBitStringSupport.buildChargeMap(mzArray, chArray));

		assertEquals(100.91263, peaks.firstKey(), 1e-4);
		assertEquals(654.00000, peaks.firstEntry().getValue(), 1e-4);

		assertEquals(759.17698, peaks.lastKey(), 1e-4);
		assertEquals(568, peaks.lastEntry().getValue(), 1e-4);
		
		assertEquals(129.39695, charges.firstKey(), 1e-4);
		assertEquals(2, charges.firstEntry().getValue().intValue());
	}
}
