package de.mpa.graphdb.edges;

public enum RelationType {
	HAS_PEPTIDE,
	IS_MATCH_IN,
	BELONGS_TO,
	BELONGS_TO_ENZYME,
	BELONGS_TO_PATHWAY,
	INVOLVED_IN_BIOPROCESS,
	BELONGS_TO_CELL_COMP,
	HAS_MOLECULAR_FUNCTION,
	IS_SUPERGROUP_OF,
	IS_ANCESTOR_OF
	
}
