
package de.mpa.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import de.mpa.client.settings.ConnectionParameters;
import de.mpa.client.settings.ParameterMap;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerImplService", targetNamespace = "http://webservice.mpa.de/", wsdlLocation = "http://metaprot:" + ConnectionParameters.DEFAULT_SRV_PORT + "/WS/Server?wsdl")
public class ServerImplService
    extends Service
{

    private final static URL SERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERIMPLSERVICE_EXCEPTION;
    private final static QName SERVERIMPLSERVICE_QNAME = new QName("http://webservice.mpa.de/", "ServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            ParameterMap params = Client.getInstance().getConnectionParameters();  
			Object address = params.get("srvAddress").getValue();
            Object srvPort = params.get("srvPort").getValue();
			url = new URL("http://" + address +":" + srvPort + "/WS/Server?wsdl");
        } catch (MalformedURLException ex) {
            throw new WebServiceException(ex);
        }
        SERVERIMPLSERVICE_WSDL_LOCATION = url;
        SERVERIMPLSERVICE_EXCEPTION = e;
    }

    public ServerImplService() throws WebServiceException {
        super(__getWsdlLocation(), SERVERIMPLSERVICE_QNAME);
    }

    public ServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERIMPLSERVICE_QNAME, features);
    }

    public ServerImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVERIMPLSERVICE_QNAME);
    }

    public ServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERIMPLSERVICE_QNAME, features);
    }

    public ServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "ServerImplPort")
    public Server getServerImplPort() {
        return super.getPort(new QName("http://webservice.mpa.de/", "ServerImplPort"), Server.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Server
     */
    @WebEndpoint(name = "ServerImplPort")
    public Server getServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.mpa.de/", "ServerImplPort"), Server.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERIMPLSERVICE_EXCEPTION!= null) {
            throw SERVERIMPLSERVICE_EXCEPTION;
        }
        return SERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
